services:
  - type: web
    name: tcp-friend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y unzip
      unzip new.zip -d .
      pip install -r requirements.txt
    startCommand: python TcP-FrEinD.py
    autoDeploy: true
